/**
 * `applyBrand` is the entire security boundary for Mode A white-labelling:
 * a hardcoded allowlist of CSS custom-property names, hex-only values, and
 * `setProperty` calls — never a CSS string, never a `<style>` tag, never
 * `innerHTML`. These tests exist to keep that boundary honest under change:
 *
 *   - the allowlist must track the schema (a forgotten new palette key is a
 *     silent no-op for that colour, not a build failure, unless something
 *     asserts completeness);
 *   - only the 18 named properties may ever be touched, no matter what a
 *     config or a hostile cache contains;
 *   - an inline brand palette outranks every stylesheet rule, so it has to
 *     be re-applied per resolved theme or light mode breaks;
 *   - the localStorage cache is a paint cache, not a source of truth, and
 *     has to survive being corrupted or hand-edited without ever reaching
 *     `setProperty` with something that isn't a hex colour.
 */

import { beforeEach, describe, expect, it, vi } from 'vitest';
import { readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import type { BrandConfig, BrandPalette } from '@conduit/config-schema';
import {
  applyBrand,
  applyBrandPalette,
  applyBrandTheme,
  applyCachedBrand,
  clearBrand,
  clearBrandCache,
  isValidHexColor,
  PALETTE_PROPERTY_MAP,
  readBrandCache,
  writeBrandCache,
} from './applyBrand';
import { appName, brand, resetBrand } from './index';
import { readPalette, writePalette } from '../shell/uiPrefs';

const here = dirname(fileURLToPath(import.meta.url));
const CACHE_KEY = 'conduit:v1-brand';

/** A dark palette with every value distinct from the light one below, so a
 * theme-switch test can tell "swapped" apart from "coincidentally equal". */
const DARK_PALETTE: BrandPalette = {
  bg: '#0f1115',
  bgSide: '#0b0d11',
  card: '#161a21',
  cardHi: '#1d222b',
  line: '#252b36',
  lineSoft: '#1b202a',
  lineHi: '#333a47',
  ink: '#e8eaed',
  ink2: '#a8aeb8',
  ink3: '#6f7681',
  hue: '#e4572e',
  hueText: '#ff8a61',
  hueSolid: '#e4572e',
  onHue: '#ffffff',
  ok: '#3fb950',
  warn: '#d29922',
  err: '#f85149',
  link: '#58a6ff',
};

const LIGHT_PALETTE: BrandPalette = {
  bg: '#fdfcf9',
  bgSide: '#f4f2ea',
  card: '#ffffff',
  cardHi: '#f5f4ee',
  line: '#e4e1d7',
  lineSoft: '#edeae1',
  lineHi: '#cfcbbf',
  ink: '#20201d',
  ink2: '#59564c',
  ink3: '#706c61',
  hue: '#b0431f',
  hueText: '#b0431f',
  hueSolid: '#bd5836',
  onHue: '#ffffff',
  ok: '#147c3b',
  warn: '#af5109',
  err: '#b91c1c',
  link: '#1f5fa8',
};

function makeConfig(overrides: Partial<BrandConfig> = {}): BrandConfig {
  return {
    schemaVersion: 1,
    identity: {
      appName: 'Northwind',
      displayName: 'Northwind AI',
      tagline: 'Message Northwind…',
    },
    palette: { dark: DARK_PALETTE, light: LIGHT_PALETTE },
    ...overrides,
  };
}

/** Every property this module is allowed to touch, for negative assertions. */
const ALLOWLISTED_PROPS = new Set(Object.values(PALETTE_PROPERTY_MAP));

beforeEach(() => {
  localStorage.clear();
  for (const prop of ALLOWLISTED_PROPS) {
    document.documentElement.style.removeProperty(prop);
  }
  // Not in ALLOWLISTED_PROPS (derived, not schema-mapped) — has to be
  // cleaned up separately or a --hue-weak set by one test leaks into the
  // next test's "started from nothing" assumptions.
  document.documentElement.style.removeProperty('--hue-weak');
  document.documentElement.removeAttribute('data-palette');
  resetBrand();
});

describe('allowlist completeness (Guard-adjacent: keeps the map in sync with the schema)', () => {
  // Without this, a new BrandPalette field compiles fine (the map's type is
  // Record<keyof BrandPalette, string>, so TS *would* catch a missing key —
  // but only at the definition site, and only if someone runs the type
  // checker before shipping). This test reads the generated schema source
  // directly, the same way Guard G6/G8/G9 read their own source files,
  // so a drift shows up as a failing assertion with the exact missing key
  // named, not as a cryptic tsc error three files away.
  it('maps every BrandPalette key generated by ts-rs', () => {
    const schemaPath = join(
      here,
      '..',
      '..',
      '..',
      '..',
      'packages',
      'config-schema',
      'src',
      'generated',
      'brand_palette.ts',
    );
    const source = readFileSync(schemaPath, 'utf8');
    const schemaKeys = Array.from(source.matchAll(/^(\w+): string,/gm)).map((m) => m[1]);

    expect(schemaKeys.length, 'regex found no fields — brand_palette.ts format changed').toBeGreaterThan(0);
    expect(Object.keys(PALETTE_PROPERTY_MAP).sort()).toEqual([...schemaKeys].sort());
  });

  it('maps exactly 18 keys — the curated surface the plan documents, not the full 124', () => {
    expect(Object.keys(PALETTE_PROPERTY_MAP)).toHaveLength(18);
  });

  it('does not map --hue-weak — it is a derived output, not a BrandPalette field', () => {
    // --hue-weak deliberately has no schema key: unlike the four --hue-a*
    // tints, tokens.css cannot derive it from var(--hue) once a brand is
    // active (see deriveHueWeak's doc comment in applyBrand.ts), so
    // applyBrandTheme computes and sets it directly instead of routing it
    // through this map. If it ever gets added here, the completeness test
    // above would demand a matching BrandPalette.hueWeak field that the
    // schema — correctly — does not have.
    expect(Object.values(PALETTE_PROPERTY_MAP)).not.toContain('--hue-weak');
  });
});

describe('isValidHexColor', () => {
  it('accepts #rgb, #rrggbb, #rrggbbaa', () => {
    expect(isValidHexColor('#fff')).toBe(true);
    expect(isValidHexColor('#ff0080')).toBe(true);
    expect(isValidHexColor('#ff008080')).toBe(true);
  });

  it('rejects anything that is not that exact grammar', () => {
    // Each of these is here because it is the specific escape shape the
    // grammar exists to close off, not a generic fuzz case.
    expect(isValidHexColor('red')).toBe(false); // named colour, not hex
    expect(isValidHexColor('rgb(0,0,0)')).toBe(false); // functional notation
    expect(isValidHexColor('url(evil.css)')).toBe(false); // the one v1 is designed to make inexpressible
    expect(isValidHexColor('var(--evil)')).toBe(false); // var() reference
    expect(isValidHexColor('javascript:alert(1)')).toBe(false);
    expect(isValidHexColor('#12')).toBe(false); // wrong length
    expect(isValidHexColor('#gggggg')).toBe(false); // out-of-range digits
    expect(isValidHexColor('')).toBe(false);
    expect(isValidHexColor(undefined)).toBe(false);
    expect(isValidHexColor(42)).toBe(false);
  });
});

describe('applyBrandPalette — the setProperty loop', () => {
  it('sets every allowlisted property to the matching palette value', () => {
    applyBrandPalette(DARK_PALETTE);
    const style = document.documentElement.style;
    expect(style.getPropertyValue('--bg')).toBe('#0f1115');
    expect(style.getPropertyValue('--hue')).toBe('#e4572e');
    expect(style.getPropertyValue('--link')).toBe('#58a6ff');
  });

  it('only ever calls setProperty with an allowlisted property name', () => {
    // This is the assertion that makes the security claim ("a fixed set of
    // properties") a tested fact rather than a comment. A future edit that
    // starts deriving property names from config keys (e.g. `--${key}`)
    // would fail this immediately instead of shipping a silent hole.
    const spy = vi.spyOn(document.documentElement.style, 'setProperty');
    applyBrandPalette(DARK_PALETTE);
    expect(spy).toHaveBeenCalled();
    for (const call of spy.mock.calls) {
      expect(ALLOWLISTED_PROPS.has(call[0])).toBe(true);
    }
    spy.mockRestore();
  });

  it('never sets the derived hue tints, and leaves --hue-weak to applyBrandTheme', () => {
    // tokens.css:233-236 derives --hue-a08/a12/a20/a40 from --hue via
    // color-mix() with no [data-provider] override, so applyBrandPalette
    // (the raw 18-key loop) must never set them — an inline override here
    // would fight that derivation. --hue-weak is different: it is a real
    // derived output, just not one applyBrandPalette produces — that is
    // applyBrandTheme's job (see the "theme coupling" tests below), so this
    // low-level function must not touch it either, for the same "only the
    // allowlisted 18" reason as the tints.
    applyBrandPalette(DARK_PALETTE);
    for (const prop of ['--hue-a08', '--hue-a12', '--hue-a20', '--hue-a40', '--hue-weak']) {
      expect(document.documentElement.style.getPropertyValue(prop)).toBe('');
    }
  });

  it('drops an individual out-of-grammar value instead of applying or throwing', () => {
    const hostile: BrandPalette = { ...DARK_PALETTE, hue: 'javascript:alert(1)' };
    expect(() => applyBrandPalette(hostile)).not.toThrow();
    expect(document.documentElement.style.getPropertyValue('--hue')).toBe('');
    // The rest of the palette still applies — one bad value doesn't sink the apply.
    expect(document.documentElement.style.getPropertyValue('--bg')).toBe('#0f1115');
  });

  it('ignores keys on the object that are not in the allowlist', () => {
    const withExtra = { ...DARK_PALETTE, evil: '#000000' } as BrandPalette & { evil: string };
    applyBrandPalette(withExtra);
    // Iteration is driven by PALETTE_PROPERTY_MAP's fixed key list, not by
    // Object.keys(palette), so an extra field never reaches setProperty at
    // all — nothing named "evil" or "--evil" should exist on the element.
    expect(document.documentElement.style.getPropertyValue('--evil')).toBe('');
    expect(document.documentElement.getAttribute('style') ?? '').not.toContain('evil');
  });
});

describe('theme coupling', () => {
  it('applyBrandTheme applies only the given theme\'s palette and sets data-palette="brand"', () => {
    applyBrandTheme(makeConfig(), 'dark');
    expect(document.documentElement.style.getPropertyValue('--bg')).toBe(DARK_PALETTE.bg);
    expect(document.documentElement.getAttribute('data-palette')).toBe('brand');
  });

  it('switching the resolved theme swaps every value to the other palette', () => {
    // Inline styles on <html> outrank [data-theme="light"], which is why a
    // single "apply once" call would break light mode — this proves the
    // fix: the caller re-invoking per resolved theme is what keeps light
    // mode correct.
    const config = makeConfig();
    applyBrandTheme(config, 'dark');
    expect(document.documentElement.style.getPropertyValue('--bg')).toBe(DARK_PALETTE.bg);
    expect(document.documentElement.style.getPropertyValue('--link')).toBe(DARK_PALETTE.link);

    applyBrandTheme(config, 'light');
    expect(document.documentElement.style.getPropertyValue('--bg')).toBe(LIGHT_PALETTE.bg);
    expect(document.documentElement.style.getPropertyValue('--link')).toBe(LIGHT_PALETTE.link);
    expect(document.documentElement.style.getPropertyValue('--bg')).not.toBe(DARK_PALETTE.bg);
  });

  it('a config with no palette (identity-only rebrand) leaves the palette axis untouched', () => {
    const config = makeConfig({ palette: undefined });
    applyBrandTheme(config, 'dark');
    expect(document.documentElement.style.getPropertyValue('--bg')).toBe('');
    expect(document.documentElement.getAttribute('data-palette')).toBeNull();
    expect(document.documentElement.style.getPropertyValue('--hue-weak')).toBe('');
  });

  it("derives --hue-weak as a 14% color-mix of the theme's hue, not the schema value verbatim", () => {
    // Regression coverage for a real bug: tokens.css does not derive
    // --hue-weak from var(--hue) anywhere reachable once data-palette="brand"
    // is set (:root's own value is the literal "transparent", the
    // [data-provider] blocks set it from their own hardcoded hex, and the
    // one var()-based rule lives inside the orange-charcoal palette block,
    // which "brand" disables). Left unhandled, chips/avatars/selection would
    // keep showing whichever provider's wash — or nothing at all — instead
    // of tracking the brand accent.
    applyBrandTheme(makeConfig(), 'dark');
    expect(document.documentElement.style.getPropertyValue('--hue-weak')).toBe(
      `color-mix(in srgb, ${DARK_PALETTE.hue} 14%, transparent)`,
    );
  });

  it('--hue-weak tracks the theme swap along with the rest of the palette', () => {
    const config = makeConfig();
    applyBrandTheme(config, 'dark');
    expect(document.documentElement.style.getPropertyValue('--hue-weak')).toBe(
      `color-mix(in srgb, ${DARK_PALETTE.hue} 14%, transparent)`,
    );

    applyBrandTheme(config, 'light');
    expect(document.documentElement.style.getPropertyValue('--hue-weak')).toBe(
      `color-mix(in srgb, ${LIGHT_PALETTE.hue} 14%, transparent)`,
    );
  });

  it('--hue-weak is not derived from an out-of-grammar hue — cleared instead of built from garbage', () => {
    const hostilePalette: BrandPalette = { ...DARK_PALETTE, hue: 'javascript:alert(1)' };
    const config = makeConfig({ palette: { dark: hostilePalette, light: LIGHT_PALETTE } });
    applyBrandTheme(config, 'dark');
    expect(document.documentElement.style.getPropertyValue('--hue')).toBe('');
    expect(document.documentElement.style.getPropertyValue('--hue-weak')).toBe('');
  });
});

describe('applyBrand — full apply (identity + palette + cache)', () => {
  it('wires identity through the Phase 0 singleton', () => {
    applyBrand(makeConfig(), 'dark');
    expect(appName()).toBe('Northwind');
    expect(brand().displayName).toBe('Northwind AI');
    expect(brand().tagline).toBe('Message Northwind…');
  });

  it('caches the applied config for the pre-paint boot path', () => {
    applyBrand(makeConfig(), 'dark');
    expect(localStorage.getItem(CACHE_KEY)).not.toBeNull();
    expect(readBrandCache()?.identity.appName).toBe('Northwind');
  });
});

describe('clearBrand — full revert', () => {
  it('removes every allowlisted property, the derived --hue-weak, resets identity, and drops the cache', () => {
    applyBrand(makeConfig(), 'dark');
    expect(document.documentElement.style.getPropertyValue('--bg')).not.toBe('');
    expect(document.documentElement.style.getPropertyValue('--hue-weak')).not.toBe('');

    clearBrand();

    for (const prop of ALLOWLISTED_PROPS) {
      expect(document.documentElement.style.getPropertyValue(prop)).toBe('');
    }
    // Derived, not in ALLOWLISTED_PROPS (that set is built from
    // PALETTE_PROPERTY_MAP, which deliberately excludes --hue-weak) — this
    // is the assertion that actually catches clearBrand forgetting it.
    expect(document.documentElement.style.getPropertyValue('--hue-weak')).toBe('');
    expect(appName()).toBe('Conduit'); // back to the built-in identity
    expect(readBrandCache()).toBeNull();
  });

  it('restores the user\'s stored palette preference rather than a hardcoded default', () => {
    // This is the one that matters most for correctness: the palette pref
    // (terra / orange-charcoal) is a user choice that predates and outlives
    // any brand. If clearBrand() reset it, turning branding off would also
    // silently discard the user's own look — a second, unrelated regression
    // hiding inside the brand feature.
    writePalette('orange-charcoal');
    applyBrand(makeConfig(), 'dark');
    expect(document.documentElement.getAttribute('data-palette')).toBe('brand');

    clearBrand();
    expect(document.documentElement.getAttribute('data-palette')).toBe('orange-charcoal');
    expect(readPalette()).toBe('orange-charcoal'); // localStorage itself was never touched
  });
});

describe('the pre-paint cache — round-trip', () => {
  it('writeBrandCache then readBrandCache returns an equivalent config', () => {
    const config = makeConfig();
    writeBrandCache(config);
    expect(readBrandCache()).toEqual(config);
  });

  it('clearBrandCache removes it', () => {
    writeBrandCache(makeConfig());
    clearBrandCache();
    expect(readBrandCache()).toBeNull();
  });

  // `notes` is brand.md's prose design-rationale body — free-form Markdown
  // with no size ceiling, unlike the palette. It has no role in painting
  // (see the module comment's "the cache is a PROJECTION" section), so
  // writeBrandCache must drop it before serializing, not merely leave it
  // unread. Without that projection, a verbose or model-generated brand
  // file would routinely exceed MAX_CACHE_CHARS and silently disable the
  // pre-paint cache for exactly the users whose brand happens to be wordy —
  // a bug that would never reproduce against the terse fixtures a test
  // suite typically uses.
  it('a config with a multi-kilobyte notes body still caches successfully', () => {
    const wordyConfig = makeConfig({ notes: 'Warm, editorial, low-contrast. '.repeat(500) }); // ~15 KB of prose
    expect(wordyConfig.notes!.length).toBeGreaterThan(10_000);

    writeBrandCache(wordyConfig);

    // Projected identity/palette still round-trip correctly even though the
    // multi-KB notes field was dropped from what got serialized.
    const cached = readBrandCache();
    expect(cached).not.toBeNull();
    expect(cached?.identity.appName).toBe('Northwind');
    expect(cached?.palette?.dark).toEqual(DARK_PALETTE);
  });

  it('the written cache entry contains no notes and no logo, regardless of what the source config carried', () => {
    const config = makeConfig({
      notes: 'Design rationale that must never reach localStorage.',
      logo: { file: 'logo.png' },
    });
    writeBrandCache(config);

    const raw = localStorage.getItem(CACHE_KEY);
    expect(raw).not.toBeNull();
    expect(raw).not.toContain('notes');
    expect(raw).not.toContain('logo.png');

    const parsed = JSON.parse(raw!);
    expect(Object.keys(parsed).sort()).toEqual(['identity', 'palette', 'schemaVersion']);
  });

  it('applyCachedBrand still applies the correct palette for both themes when notes was present at write time', () => {
    const config = makeConfig({ notes: 'x'.repeat(5000) });
    writeBrandCache(config);

    applyCachedBrand('dark');
    expect(document.documentElement.style.getPropertyValue('--bg')).toBe(DARK_PALETTE.bg);

    applyCachedBrand('light');
    expect(document.documentElement.style.getPropertyValue('--bg')).toBe(LIGHT_PALETTE.bg);
  });

  // Phase 2 added a large-value hazard next door: the brand logo can be up
  // to ~2.7 MiB base64. It is never routed through writeBrandCache (see the
  // module comment's "why the logo is never cached" section and
  // brand/logo.ts) — but this guard exists so that if something ever did
  // try to smuggle a large value in here (a bad merge, a future field), the
  // write is skipped instead of risking a QuotaExceededError that could
  // sink this *palette* cache entry too. Without this test, a regression
  // that let an oversized value through would only surface as an
  // intermittent quota failure in a real browser — not in jsdom, which
  // doesn't enforce localStorage's quota at all.
  //
  // This bloats `identity.displayName`, not `notes` — `identity` survives
  // the write-time projection (only `notes`/`logo` are dropped), so this
  // fixture is still genuinely oversized *after* projection and this guard
  // is still doing real work. A fixture that instead bloated `notes` would
  // now be projected away before the size check ever runs and would prove
  // nothing.
  it('refuses to write an oversized value, leaving any existing cache entry untouched', () => {
    const config = makeConfig();
    writeBrandCache(config);
    expect(readBrandCache()).toEqual(config);

    // A palette entry with an implausibly long value simulates "something
    // oversized landed in BrandConfig" without needing a real 2 MiB payload.
    const oversized = makeConfig({
      identity: { appName: 'X', displayName: 'X'.repeat(20_000), tagline: 'X' },
    });
    writeBrandCache(oversized);

    // The oversized write was dropped — the previous good entry is still there.
    expect(readBrandCache()).toEqual(config);
  });

  it('an oversized write never throws', () => {
    const oversized = makeConfig({
      identity: { appName: 'X', displayName: 'X'.repeat(20_000), tagline: 'X' },
    });
    expect(() => writeBrandCache(oversized)).not.toThrow();
  });

  it('applyCachedBrand replays identity + the theme-appropriate palette without re-writing the cache', () => {
    const config = makeConfig();
    writeBrandCache(config);
    const before = localStorage.getItem(CACHE_KEY);

    const applied = applyCachedBrand('light');

    expect(applied?.identity.appName).toBe('Northwind');
    expect(document.documentElement.style.getPropertyValue('--bg')).toBe(LIGHT_PALETTE.bg);
    expect(appName()).toBe('Northwind');
    // Replaying from the cache does not touch the cache itself.
    expect(localStorage.getItem(CACHE_KEY)).toBe(before);
  });

  it('applyCachedBrand is a no-op (returns null, touches nothing) with no cache present', () => {
    expect(applyCachedBrand('dark')).toBeNull();
    expect(document.documentElement.style.getPropertyValue('--bg')).toBe('');
    expect(appName()).toBe('Conduit');
  });
});

describe('the pre-paint cache — corrupt / hostile entries are rejected, not partially applied', () => {
  // This whole block exists because the cache is the one input in this
  // module that is *not* freshly Rust-validated on every use: it round-trips
  // through JSON in localStorage, which anything running in the renderer
  // (or a hand-edited devtools session) can write to directly. Without these
  // checks a corrupted or hand-crafted entry would either throw during boot
  // (breaking the pre-paint path entirely) or get applied as-is.

  it('rejects invalid JSON outright', () => {
    localStorage.setItem(CACHE_KEY, '{not json');
    expect(readBrandCache()).toBeNull();
    expect(() => applyCachedBrand('dark')).not.toThrow();
    expect(applyCachedBrand('dark')).toBeNull();
  });

  it('rejects a value of the wrong shape (array, primitive, missing identity)', () => {
    localStorage.setItem(CACHE_KEY, JSON.stringify([1, 2, 3]));
    expect(readBrandCache()).toBeNull();

    localStorage.setItem(CACHE_KEY, JSON.stringify('just a string'));
    expect(readBrandCache()).toBeNull();

    localStorage.setItem(CACHE_KEY, JSON.stringify({ schemaVersion: 1 })); // no identity
    expect(readBrandCache()).toBeNull();
  });

  it('rejects a palette missing a required key rather than applying it with a hole', () => {
    // A half-shaped palette is exactly the "unreadable text" hazard the
    // Rust validator's dark/light symmetry check exists to prevent — and
    // the cache bypasses that validator, so this module has to re-check it.
    const { err: _dropped, ...darkMissingErr } = DARK_PALETTE;
    const hostile = makeConfig({ palette: { dark: darkMissingErr as BrandPalette, light: LIGHT_PALETTE } });
    localStorage.setItem(CACHE_KEY, JSON.stringify(hostile));
    expect(readBrandCache()).toBeNull();
  });

  it('accepts the shape but still drops an out-of-grammar colour value at apply time', () => {
    // Structural validation passes (every key is a string) but one value
    // is not a hex colour — this must never reach setProperty.
    const hostile = makeConfig({
      palette: {
        dark: { ...DARK_PALETTE, bg: 'url(https://evil.example/x.css)' },
        light: LIGHT_PALETTE,
      },
    });
    localStorage.setItem(CACHE_KEY, JSON.stringify(hostile));

    // The structural check alone doesn't reject this — only the per-value
    // hex check at apply time does.
    expect(readBrandCache()).not.toBeNull();

    applyCachedBrand('dark');
    expect(document.documentElement.style.getPropertyValue('--bg')).toBe('');
    // Everything else in the same palette still applies.
    expect(document.documentElement.style.getPropertyValue('--hue')).toBe(DARK_PALETTE.hue);
  });

  it('rejects a non-numeric schemaVersion', () => {
    const hostile = { ...makeConfig(), schemaVersion: 'one' };
    localStorage.setItem(CACHE_KEY, JSON.stringify(hostile));
    expect(readBrandCache()).toBeNull();
  });

  it('a storage read that throws (e.g. storage disabled) is treated as "no cache", not a crash', () => {
    const spy = vi.spyOn(Storage.prototype, 'getItem').mockImplementation(() => {
      throw new Error('storage disabled');
    });
    expect(() => readBrandCache()).not.toThrow();
    expect(readBrandCache()).toBeNull();
    spy.mockRestore();
  });
});
