//! MCP JSON-RPC 2.0 protocol framing and typed discovery result shapes.
//!
//! This module is transport-agnostic: it knows how to encode/decode the
//! newline-delimited JSON-RPC messages MCP servers speak, and the typed
//! results of `initialize` / `tools|resources|prompts/list` / `tools/call`.
//! It does not know how those messages are carried (stdio, HTTP/SSE, ...) —
//! that is the `transport` module's job.
//!
//! A connector-declared `permissionLevel` is an *optional* extra field on a
//! tool listing. Standard MCP does not define it; when a tenant connector
//! declares it the runtime honors it, otherwise the consent engine defaults
//! the tool to read-only (never silently side-effectful).

use serde::{Deserialize, Serialize};
use serde_json::Value;

// Re-export the canonical consent-tier enum so the whole stack shares one
// source of truth for `ReadOnly | SideEffectful | Sensitive`.
pub use provider_core::schema::PermissionLevel;

/// MCP protocol version advertised by the client in `initialize`.
pub const PROTOCOL_VERSION: &str = "2024-11-05";

// --- JSON-RPC envelope -------------------------------------------------------

/// JSON-RPC 2.0 request id. MCP servers accept integers or strings; we use
/// incrementing integers generated by the transport.
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(untagged)]
pub enum RequestId {
    Num(u64),
    Str(String),
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct JsonRpcRequest {
    pub jsonrpc: String,
    pub id: RequestId,
    pub method: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub params: Option<Value>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct JsonRpcError {
    pub code: i64,
    pub message: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub data: Option<Value>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct JsonRpcResponse {
    pub jsonrpc: String,
    pub id: RequestId,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub result: Option<Value>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub error: Option<JsonRpcError>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct JsonRpcNotification {
    pub jsonrpc: String,
    pub method: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub params: Option<Value>,
}

/// One framed message the transport may receive on its input stream. A
/// response matches a pending request by `id`; notifications and server-side
/// requests are passed through for logging/ignoring.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum JsonRpcMessage {
    Response(JsonRpcResponse),
    Notification(JsonRpcNotification),
    Request(JsonRpcRequest),
}

// --- initialize --------------------------------------------------------------

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ClientInfo {
    pub name: String,
    pub version: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ServerInfo {
    pub name: String,
    pub version: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct InitializeResult {
    pub protocol_version: String,
    pub server_info: ServerInfo,
}

// --- discovery ---------------------------------------------------------------

/// A tool discovered from a connector. `permission_level` is the optional
/// tenant-declared consent tier; absent means "unspecified" (the consent
/// engine treats that as read-only).
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct McpTool {
    pub name: String,
    #[serde(default)]
    pub description: String,
    #[serde(rename = "inputSchema")]
    pub input_schema: Value,
    /// Optional consent tier declared by the connector. Not part of base MCP.
    #[serde(
        rename = "permissionLevel",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub permission_level: Option<PermissionLevel>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct McpResource {
    pub uri: String,
    pub name: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct McpPrompt {
    pub name: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
}

// --- tools/call result -------------------------------------------------------

/// One content item in a `tools/call` result. MVP models text plus a generic
/// fallback so unknown content types (images, embedded resources) survive as
/// data without being interpreted.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", tag = "type")]
pub enum ToolContent {
    Text {
        text: String,
    },
    /// Any other content type — preserved verbatim as untrusted data.
    Other {
        #[serde(flatten)]
        raw: Value,
    },
}

/// The typed result of a `tools/call`. `size_bytes` and `mime_hints` are
/// computed by the transport from the raw content and are the Phase 5
/// artifact-handoff hints.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ToolOutput {
    pub content: Vec<ToolContent>,
    #[serde(default)]
    pub is_error: bool,
    pub size_bytes: u64,
    #[serde(default)]
    pub mime_hints: Vec<String>,
}

impl ToolOutput {
    /// Flatten text content into a single string for persistence/display.
    pub fn text_summary(&self) -> String {
        self.content
            .iter()
            .filter_map(|c| match c {
                ToolContent::Text { text } => Some(text.as_str()),
                _ => None,
            })
            .collect::<Vec<_>>()
            .join("\n")
    }
}
