// SPDX-License-Identifier: AGPL-3.0-only
// Copyright (C) 2026 Emilio Olivares

/**
 * @conduit/config-schema — TypeScript bindings for Conduit's internal schema.
 *
 * C1: Rust is the canonical source of truth. Every type below is generated by
 * `cargo run --example export_ts -p provider-core` into `./generated/` from the
 * `provider_core::schema` crate. Do not hand-edit the generated files or add
 * type definitions here — change the Rust source and re-run the export.
 *
 * Staleness is enforced by `npm run check`, which regenerates and fails if the
 * committed bindings differ from the Rust source.
 */
export const CANONICAL_SCHEMA_VERSION = 1 as const;

// Message & content
export type { MessageRole } from './generated/message_role';
export type { MessagePartKind } from './generated/message_part_kind';
export type { MessagePart } from './generated/message_part';
export type { Message } from './generated/message';
export type { Conversation } from './generated/conversation';
export type { ConversationSummary } from './generated/conversation_summary';

// Provider request / response
export type { ToolChoice } from './generated/tool_choice';
export type { GenerationControls } from './generated/generation_controls';
export type { ResponseFormatHint } from './generated/response_format_hint';
export type { ProviderRequest } from './generated/provider_request';
export type { ProviderUsage } from './generated/provider_usage';
export type { ProviderError } from './generated/provider_error';
export type { ProviderEvent } from './generated/provider_event';

// Agent web search (M-WebSearch).
export type { SearchContextSize } from './generated/search_context_size';
export type { ReturnTokenBudget } from './generated/return_token_budget';
export type { WebSearchFilters } from './generated/web_search_filters';
export type { UserLocation } from './generated/user_location';
export type { WebSearchRequest } from './generated/web_search_request';
export type { WebSearchDefaults } from './generated/web_search_defaults';
export type { ContentAnnotation } from './generated/content_annotation';

// Tools
export type { PermissionLevel } from './generated/permission_level';
export type { ToolKind } from './generated/tool_kind';
export type { ToolDefinition } from './generated/tool_definition';
export type { ToolCallStatus } from './generated/tool_call_status';
export type { ToolCallRecord } from './generated/tool_call_record';

// Artifacts
export type { ArtifactKind } from './generated/artifact_kind';
export type { Artifact } from './generated/artifact';

// Attachments
export type { RetentionState } from './generated/retention_state';
export type { Attachment } from './generated/attachment';

// Tenant & connector
export type { TenantIdentity } from './generated/tenant_identity';
export type { ModelPolicy } from './generated/model_policy';
export type { TenantConfig } from './generated/tenant_config';
export type { Transport } from './generated/transport';
export type { ConnectorDefinition } from './generated/connector_definition';
export type { RolloutChannel } from './generated/rollout_channel';
export type { SupportState } from './generated/support_state';
export type { ConnectorVersion } from './generated/connector_version';
export type { GrantScope } from './generated/grant_scope';
export type { GrantStatus } from './generated/grant_status';
export type { ConnectorGrant } from './generated/connector_grant';

// Phase 4 — MCP runtime / consent IPC
export type { ConsentDecision } from './generated/consent_decision';
export type { ConsentPrompt } from './generated/consent_prompt';
export type { ConnectorRuntimeEvent } from './generated/connector_runtime_event';

// License
export type { LicenseClaims } from './generated/license_claims';

// App shell configuration (IPC schema)
export type { Theme } from './generated/theme';
export type { ProviderEndpointConfig } from './generated/provider_endpoint_config';
export type { AgentGuardrails } from './generated/agent_guardrails';
export type { AppSettings } from './generated/app_settings';
export type { SettingsPatch } from './generated/settings_patch';
export type { ModelInfo } from './generated/model_info';
export type { CredentialRequest } from './generated/credential_request';
export type { CredentialSummary } from './generated/credential_summary';