//! M1: each shipped fixture DB (one snapshot per released schema version, under
//! `tests/fixtures/db/`) migrates forward and passes the integrity check.
//!
//! Fixtures are generated by `generate-migration-fixture` (synthetic historical
//! snapshots) or `tests/fixtures/regenerate.sh` (release-tag snapshots). The
//! suite fails if the fixture directory exists but contains no `.sqlite` files.

use conduit_desktop::db;
use sqlx::sqlite::SqlitePoolOptions;
use std::{fs, path::PathBuf};

fn fixtures_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests").join("fixtures").join("db")
}

#[tokio::test]
async fn every_fixture_migrates_and_is_internally_consistent() {
    let dir = fixtures_dir();
    assert!(
        dir.exists(),
        "fixture directory missing at {} — run generate-migration-fixture",
        dir.display()
    );

    let mut count = 0;
    for entry in fs::read_dir(&dir).expect("read fixtures dir") {
        let entry = entry.expect("dir entry");
        let path = entry.path();
        if path.extension().and_then(|e| e.to_str()) != Some("sqlite") {
            continue;
        }
        count += 1;

        let url = format!(
            "sqlite://{}?mode=rwc",
            path.to_string_lossy().replace('\\', "/")
        );
        let pool = SqlitePoolOptions::new()
            .max_connections(1)
            .connect(&url)
            .await
            .unwrap_or_else(|e| panic!("open fixture {}: {e}", path.display()));

        db::run_migrations(&pool)
            .await
            .unwrap_or_else(|e| panic!("migrate fixture {}: {e}", path.display()));
        db::migrations::reconcile_on_startup(&pool)
            .await
            .unwrap_or_else(|e| panic!("reconcile fixture {}: {e}", path.display()));
    }

    assert!(
        count > 0,
        "expected at least one .sqlite fixture in {}",
        dir.display()
    );
    eprintln!("fixture_migration: verified {count} fixture DB(s)");
}