#!/usr/bin/env node
// Keeps the localized READMEs linked to each other and honest about their age.
//
//   node scripts/readme-i18n.mjs --write   rewrite the language selector in all READMEs
//   node scripts/readme-i18n.mjs --check   fail if a selector is stale or a translation
//                                          lags the English README (CI uses this)
//
// GitHub has no native localized-README support: only README.md renders on the
// repo landing page, and nothing keeps translations in step. So the selector is
// generated rather than hand-maintained, and every translation carries the
// English commit it was made from.
//
// Locale codes match i18n/locales.json in the website repo — one vocabulary
// across both properties.

import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { execFileSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');

export const LOCALES = [
  { code: 'en', name: 'English', file: 'README.md', site: '' },
  { code: 'de', name: 'Deutsch', file: 'README.de.md', site: '/de' },
  { code: 'es', name: 'Español', file: 'README.es.md', site: '/es' },
  { code: 'fr', name: 'Français', file: 'README.fr.md', site: '/fr' },
  { code: 'ja', name: '日本語', file: 'README.ja.md', site: '/ja' },
  { code: 'ko', name: '한국어', file: 'README.ko.md', site: '/ko' },
  { code: 'pt-BR', name: 'Português (Brasil)', file: 'README.pt-BR.md', site: '/pt-BR' },
  { code: 'zh-CN', name: '简体中文', file: 'README.zh-CN.md', site: '/zh-CN' },
];

const NAV_START = '<!-- i18n-nav:start -->';
const NAV_END = '<!-- i18n-nav:end -->';
const NAV_NOTE = '<!-- Generated by scripts/readme-i18n.mjs — do not edit by hand. -->';
const STAMP = /<!--\s*i18n-source:\s*([0-9a-f]{7,40})\s*-->/;

// The current locale is bold text, not a link: each file shows the reader where
// they already are.
function navFor(code) {
  const row = LOCALES.map((l) =>
    l.code === code ? `**${l.name}**` : `[${l.name}](./${l.file})`,
  ).join(' &nbsp;·&nbsp; ');
  return [NAV_START, NAV_NOTE, '', row, '', NAV_END].join('\n');
}

const read = (f) => readFileSync(join(ROOT, f), 'utf8');
const git = (...args) => execFileSync('git', args, { cwd: ROOT, encoding: 'utf8' }).trim();

function replaceNav(text, code) {
  const nav = navFor(code);
  const i = text.indexOf(NAV_START);
  const j = text.indexOf(NAV_END);
  if (i !== -1 && j > i) {
    return text.slice(0, i) + nav + text.slice(j + NAV_END.length);
  }
  // No block yet — the selector has to be the first thing in the file, because
  // a reader who cannot find it never sees their language exists.
  const stamp = text.match(STAMP);
  if (stamp && text.trimStart().startsWith('<!--')) {
    const after = text.indexOf('\n', text.indexOf(stamp[0]));
    return `${text.slice(0, after + 1)}\n${nav}\n${text.slice(after + 1).replace(/^\n+/, '')}`;
  }
  return `${nav}\n\n${text.replace(/^\n+/, '')}`;
}

function write() {
  let changed = 0;
  for (const { code, file } of LOCALES) {
    if (!existsSync(join(ROOT, file))) {
      console.log(`  skip  ${file} (not written yet)`);
      continue;
    }
    const before = read(file);
    const after = replaceNav(before, code);
    if (before !== after) {
      writeFileSync(join(ROOT, file), after, 'utf8');
      changed++;
      console.log(`  wrote ${file}`);
    } else {
      console.log(`  ok    ${file}`);
    }
  }
  console.log(changed ? `\n${changed} file(s) updated.` : '\nAll selectors already current.');
}

function check() {
  const problems = [];
  const englishRev = git('log', '-1', '--format=%H', '--', 'README.md');
  const shortEnglish = englishRev.slice(0, 7);

  for (const { code, file } of LOCALES) {
    if (!existsSync(join(ROOT, file))) {
      if (code !== 'en') console.log(`  skip  ${file} (not translated yet)`);
      continue;
    }
    const text = read(file);

    if (replaceNav(text, code) !== text) {
      problems.push(`${file}: language selector is out of date — run \`node scripts/readme-i18n.mjs --write\``);
    }

    if (code === 'en') continue;

    const stamp = text.match(STAMP);
    if (!stamp) {
      problems.push(`${file}: missing an \`<!-- i18n-source: <sha> -->\` stamp`);
      continue;
    }

    const at = stamp[1];
    let known = true;
    try {
      git('cat-file', '-e', `${at}^{commit}`);
    } catch {
      known = false;
    }
    if (!known) {
      problems.push(`${file}: i18n-source ${at} is not a commit in this repository`);
    } else if (git('rev-parse', at) !== englishRev) {
      const behind = git('rev-list', '--count', `${at}..${englishRev}`, '--', 'README.md');
      if (Number(behind) > 0) {
        problems.push(
          `${file}: translated at ${at}, but README.md has moved on ${behind} commit(s) since (now ${shortEnglish})`,
        );
      }
    }
    if (!problems.some((p) => p.startsWith(file))) console.log(`  ok    ${file}`);
  }

  if (problems.length) {
    console.error('\nLocalized READMEs need attention:\n');
    for (const p of problems) console.error(`  - ${p}`);
    console.error(
      '\nAfter updating a translation, restamp it with the README.md commit it now reflects:\n' +
        `  <!-- i18n-source: ${shortEnglish} -->\n`,
    );
    process.exit(1);
  }
  console.log('\nAll localized READMEs are in step with README.md.');
}

const mode = process.argv[2];
if (mode === '--write') write();
else if (mode === '--check') check();
else {
  console.error('usage: node scripts/readme-i18n.mjs --write | --check');
  process.exit(2);
}
